language: php
php:
  - 8.0

before_script:
    - composer install --no-progress --prefer-dist

script: vendor/bin/tester tests -C -s

jobs:
  include:
    -   name: Lowest Dependencies
        install:
          - travis_retry composer update --no-progress --prefer-dist --prefer-lowest --prefer-stable


    -   name: Nette Coding Standard
        install:
          - travis_retry composer create-project nette/coding-standard temp/coding-standard ^3 --no-progress
        script:
          - php temp/coding-standard/ecs check src tests --preset php74


    -   stage: Static Analysis (informative)
        script:
          - php vendor/bin/phpstan.phar analyse src
