language: php
php:
  - 7.1
  - 7.2
  - 7.3

before_script:
    - pear config-set preferred_state beta
    - pecl channel-update pecl.php.net
    - yes | pecl install imagick
    - composer install --no-progress --prefer-dist

script: vendor/bin/tester tests -C -s

jobs:
  include:
    -   name: Lowest Dependencies
        install:
          - travis_retry composer update --no-progress --prefer-dist --prefer-lowest --prefer-stable


    -   name: Nette Coding Standard
        install:
          - travis_retry composer create-project nette/coding-standard temp/coding-standard ^2 --no-progress
        script:
          - php temp/coding-standard/ecs check src tests --config temp/coding-standard/coding-standard-php71.yml


    -   stage: Static Analysis (informative)
        install:
          # Install PHPStan
          - travis_retry composer create-project phpstan/phpstan-shim temp/phpstan --no-progress
          - travis_retry composer install --no-progress --prefer-dist
        script:
          - php temp/phpstan/phpstan.phar analyse --autoload-file vendor/autoload.php --level 7 src
