name: Code checks

on:
  push:
    branches: [ master ]
  pull_request: null

jobs:
  ecs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.0' ]
    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - run: composer install --prefer-dist --no-progress --no-suggest
      - run: composer create-project nette/coding-standard temp/coding-standard --no-progress
      - run: php temp/coding-standard/ecs check src tests --preset php74
