name: Code checks

on:
  push:
    branches: [ master ]
  pull_request: null

jobs:
  ecs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.3', 8.4' ]
    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - run: composer install --prefer-dist --no-progress --no-suggest
      - run: composer create-project janu-software/coding-standard temp/nette-coding-standard && cp ./.coding-standard/project.xml ./temp/nette-coding-standard/preset-sniffer/project.xml && cp ./.coding-standard/project.php ./temp/nette-coding-standard/preset-fixer/project.php --no-progress
      - run: php temp/coding-standard/ecs check src tests --preset project
