name: "Coverage"

on:
  pull_request:

  push:
    branches: ["*"]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  test80:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester-coverage-v2.yml
    with:
        php: "8.3"
        makefile: coverage
